server:
  port: 8086
spring:
  application:
    name: scoring-service
  datasource:
    url: jdbc:postgresql://localhost:5437/scoringdb
    username: postgres
    password: secret
  jpa:
    hibernate:
      ddl-auto: create-drop
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: scoring-service-group
      auto-offset-reset: earliest

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2000
      database: 0

scoring:
  weights:
    timeliness: 0.35
    quality: 0.35
    cost: 0.20
    responsiveness: 0.10
